apiVersion: v2
name: memoryfs
description: Distributed memory-oriented filesystem cluster
type: application
version: 0.0.0
appVersion: "latest"
home: https://github.com/shaowenchen/memoryfs
sources:
  - https://github.com/shaowenchen/memoryfs
keywords:
  - memoryfs
  - fuse
  - storage
maintainers:
  - name: shaowenchen
