// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/memoryfs/v1/memoryfs.proto

package memoryfsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ino           uint64                 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Mtime         int64                  `protobuf:"varint,6,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Nlink         uint32                 `protobuf:"varint,7,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Chunks        []string               `protobuf:"bytes,9,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attr) Reset() {
	*x = Attr{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{0}
}

func (x *Attr) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *Attr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Attr) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attr) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Attr) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Attr) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Attr) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Attr) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Attr) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeState          string                 `protobuf:"bytes,2,opt,name=node_state,json=nodeState,proto3" json:"node_state,omitempty"`
	ClusterEpoch       uint64                 `protobuf:"varint,3,opt,name=cluster_epoch,json=clusterEpoch,proto3" json:"cluster_epoch,omitempty"`
	IsLeader           bool                   `protobuf:"varint,4,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	PendingDrainChunks int32                  `protobuf:"varint,5,opt,name=pending_drain_chunks,json=pendingDrainChunks,proto3" json:"pending_drain_chunks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetNodeState() string {
	if x != nil {
		return x.NodeState
	}
	return ""
}

func (x *HealthResponse) GetClusterEpoch() uint64 {
	if x != nil {
		return x.ClusterEpoch
	}
	return 0
}

func (x *HealthResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *HealthResponse) GetPendingDrainChunks() int32 {
	if x != nil {
		return x.PendingDrainChunks
	}
	return 0
}

type GetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderRequest) Reset() {
	*x = GetLeaderRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderRequest) ProtoMessage() {}

func (x *GetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{3}
}

type GetLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        string                 `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderResponse) Reset() {
	*x = GetLeaderResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderResponse) ProtoMessage() {}

func (x *GetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{5}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	HttpAddr      string                 `protobuf:"bytes,3,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,4,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	RdmaAddr      string                 `protobuf:"bytes,5,opt,name=rdma_addr,json=rdmaAddr,proto3" json:"rdma_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *JoinRequest) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *JoinRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *JoinRequest) GetRdmaAddr() string {
	if x != nil {
		return x.RdmaAddr
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{8}
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ino           uint64                 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{9}
}

func (x *GetAttrRequest) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{10}
}

func (x *GetAttrResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{11}
}

func (x *LookupRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{12}
}

func (x *LookupResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type ReaddirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReaddirRequest) Reset() {
	*x = ReaddirRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReaddirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaddirRequest) ProtoMessage() {}

func (x *ReaddirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaddirRequest.ProtoReflect.Descriptor instead.
func (*ReaddirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{13}
}

func (x *ReaddirRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

type ReaddirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]*Attr       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReaddirResponse) Reset() {
	*x = ReaddirResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReaddirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaddirResponse) ProtoMessage() {}

func (x *ReaddirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaddirResponse.ProtoReflect.Descriptor instead.
func (*ReaddirResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{14}
}

func (x *ReaddirResponse) GetEntries() map[string]*Attr {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{15}
}

func (x *MkdirRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MkdirRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{16}
}

func (x *MkdirResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{17}
}

func (x *CreateRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{18}
}

func (x *CreateResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type SymlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkRequest) Reset() {
	*x = SymlinkRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkRequest) ProtoMessage() {}

func (x *SymlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkRequest.ProtoReflect.Descriptor instead.
func (*SymlinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{19}
}

func (x *SymlinkRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *SymlinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymlinkRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SymlinkRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SymlinkRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type SymlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkResponse) Reset() {
	*x = SymlinkResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkResponse) ProtoMessage() {}

func (x *SymlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkResponse.ProtoReflect.Descriptor instead.
func (*SymlinkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{20}
}

func (x *SymlinkResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{21}
}

func (x *UnlinkRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *UnlinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkResponse) Reset() {
	*x = UnlinkResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkResponse) ProtoMessage() {}

func (x *UnlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkResponse.ProtoReflect.Descriptor instead.
func (*UnlinkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{22}
}

func (x *UnlinkResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentIno     uint64                 `protobuf:"varint,1,opt,name=parent_ino,json=parentIno,proto3" json:"parent_ino,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{23}
}

func (x *RmdirRequest) GetParentIno() uint64 {
	if x != nil {
		return x.ParentIno
	}
	return 0
}

func (x *RmdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RmdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirResponse) Reset() {
	*x = RmdirResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirResponse) ProtoMessage() {}

func (x *RmdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirResponse.ProtoReflect.Descriptor instead.
func (*RmdirResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{24}
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldParent     uint64                 `protobuf:"varint,1,opt,name=old_parent,json=oldParent,proto3" json:"old_parent,omitempty"`
	NewParent     uint64                 `protobuf:"varint,2,opt,name=new_parent,json=newParent,proto3" json:"new_parent,omitempty"`
	OldName       string                 `protobuf:"bytes,3,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{25}
}

func (x *RenameRequest) GetOldParent() uint64 {
	if x != nil {
		return x.OldParent
	}
	return 0
}

func (x *RenameRequest) GetNewParent() uint64 {
	if x != nil {
		return x.NewParent
	}
	return 0
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{26}
}

type SetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrRequest) Reset() {
	*x = SetAttrRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrRequest) ProtoMessage() {}

func (x *SetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrRequest.ProtoReflect.Descriptor instead.
func (*SetAttrRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{27}
}

func (x *SetAttrRequest) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type SetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *Attr                  `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrResponse) Reset() {
	*x = SetAttrResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrResponse) ProtoMessage() {}

func (x *SetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrResponse.ProtoReflect.Descriptor instead.
func (*SetAttrResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{28}
}

func (x *SetAttrResponse) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type PutChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ReplicaFactor int32                  `protobuf:"varint,3,opt,name=replica_factor,json=replicaFactor,proto3" json:"replica_factor,omitempty"`
	Replica       bool                   `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	ChainId       uint32                 `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainVer      uint64                 `protobuf:"varint,7,opt,name=chain_ver,json=chainVer,proto3" json:"chain_ver,omitempty"`
	UpdateVer     uint64                 `protobuf:"varint,8,opt,name=update_ver,json=updateVer,proto3" json:"update_ver,omitempty"`
	CommitVer     uint64                 `protobuf:"varint,9,opt,name=commit_ver,json=commitVer,proto3" json:"commit_ver,omitempty"`
	Replicas      []string               `protobuf:"bytes,10,rep,name=replicas,proto3" json:"replicas,omitempty"`
	FromClient    bool                   `protobuf:"varint,11,opt,name=from_client,json=fromClient,proto3" json:"from_client,omitempty"`
	Syncing       bool                   `protobuf:"varint,12,opt,name=syncing,proto3" json:"syncing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{29}
}

func (x *PutChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutChunkRequest) GetReplicaFactor() int32 {
	if x != nil {
		return x.ReplicaFactor
	}
	return 0
}

func (x *PutChunkRequest) GetReplica() bool {
	if x != nil {
		return x.Replica
	}
	return false
}

func (x *PutChunkRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PutChunkRequest) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PutChunkRequest) GetChainVer() uint64 {
	if x != nil {
		return x.ChainVer
	}
	return 0
}

func (x *PutChunkRequest) GetUpdateVer() uint64 {
	if x != nil {
		return x.UpdateVer
	}
	return 0
}

func (x *PutChunkRequest) GetCommitVer() uint64 {
	if x != nil {
		return x.CommitVer
	}
	return 0
}

func (x *PutChunkRequest) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PutChunkRequest) GetFromClient() bool {
	if x != nil {
		return x.FromClient
	}
	return false
}

func (x *PutChunkRequest) GetSyncing() bool {
	if x != nil {
		return x.Syncing
	}
	return false
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []string               `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{30}
}

func (x *PutChunkResponse) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type GetChunkRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChunkId          string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	AllowUncommitted bool                   `protobuf:"varint,2,opt,name=allow_uncommitted,json=allowUncommitted,proto3" json:"allow_uncommitted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{31}
}

func (x *GetChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetChunkRequest) GetAllowUncommitted() bool {
	if x != nil {
		return x.AllowUncommitted
	}
	return false
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{32}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{34}
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{35}
}

func (x *DrainRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DrainResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemainingChunks int32                  `protobuf:"varint,1,opt,name=remaining_chunks,json=remainingChunks,proto3" json:"remaining_chunks,omitempty"`
	Drained         bool                   `protobuf:"varint,2,opt,name=drained,proto3" json:"drained,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{36}
}

func (x *DrainResponse) GetRemainingChunks() int32 {
	if x != nil {
		return x.RemainingChunks
	}
	return 0
}

func (x *DrainResponse) GetDrained() bool {
	if x != nil {
		return x.Drained
	}
	return false
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{37}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP(), []int{38}
}

func (x *ReadyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_memoryfs_v1_memoryfs_proto protoreflect.FileDescriptor

const file_api_proto_memoryfs_v1_memoryfs_proto_rawDesc = "" +
	"\n" +
	"$api/proto/memoryfs/v1/memoryfs.proto\x12\vmemoryfs.v1\"\xc0\x01\n" +
	"\x04Attr\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x14\n" +
	"\x05mtime\x18\x06 \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05nlink\x18\a \x01(\rR\x05nlink\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12\x16\n" +
	"\x06chunks\x18\t \x03(\tR\x06chunks\"\x0f\n" +
	"\rHealthRequest\"\xbb\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"node_state\x18\x02 \x01(\tR\tnodeState\x12#\n" +
	"\rcluster_epoch\x18\x03 \x01(\x04R\fclusterEpoch\x12\x1b\n" +
	"\tis_leader\x18\x04 \x01(\bR\bisLeader\x120\n" +
	"\x14pending_drain_chunks\x18\x05 \x01(\x05R\x12pendingDrainChunks\"\x12\n" +
	"\x10GetLeaderRequest\"+\n" +
	"\x11GetLeaderResponse\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\tR\x06leader\"\x12\n" +
	"\x10ListNodesRequest\")\n" +
	"\x11ListNodesResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\"\x91\x01\n" +
	"\vJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1b\n" +
	"\thttp_addr\x18\x03 \x01(\tR\bhttpAddr\x12\x1b\n" +
	"\tgrpc_addr\x18\x04 \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\trdma_addr\x18\x05 \x01(\tR\brdmaAddr\"\x0e\n" +
	"\fJoinResponse\"\"\n" +
	"\x0eGetAttrRequest\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\"8\n" +
	"\x0fGetAttrResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"B\n" +
	"\rLookupRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"7\n" +
	"\x0eLookupResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"/\n" +
	"\x0eReaddirRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\"\xa5\x01\n" +
	"\x0fReaddirResponse\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).memoryfs.v1.ReaddirResponse.EntriesEntryR\aentries\x1aM\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.memoryfs.v1.AttrR\x05value:\x028\x01\"y\n" +
	"\fMkdirRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\"6\n" +
	"\rMkdirResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"z\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\"7\n" +
	"\x0eCreateResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"\x7f\n" +
	"\x0eSymlinkRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\"8\n" +
	"\x0fSymlinkResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"B\n" +
	"\rUnlinkRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"7\n" +
	"\x0eUnlinkResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"A\n" +
	"\fRmdirRequest\x12\x1d\n" +
	"\n" +
	"parent_ino\x18\x01 \x01(\x04R\tparentIno\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x0f\n" +
	"\rRmdirResponse\"\x83\x01\n" +
	"\rRenameRequest\x12\x1d\n" +
	"\n" +
	"old_parent\x18\x01 \x01(\x04R\toldParent\x12\x1d\n" +
	"\n" +
	"new_parent\x18\x02 \x01(\x04R\tnewParent\x12\x19\n" +
	"\bold_name\x18\x03 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\"\x10\n" +
	"\x0eRenameResponse\"7\n" +
	"\x0eSetAttrRequest\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"8\n" +
	"\x0fSetAttrResponse\x12%\n" +
	"\x04attr\x18\x01 \x01(\v2\x11.memoryfs.v1.AttrR\x04attr\"\xe4\x02\n" +
	"\x0fPutChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12%\n" +
	"\x0ereplica_factor\x18\x03 \x01(\x05R\rreplicaFactor\x12\x18\n" +
	"\areplica\x18\x04 \x01(\bR\areplica\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\rR\achainId\x12\x1b\n" +
	"\tchain_ver\x18\a \x01(\x04R\bchainVer\x12\x1d\n" +
	"\n" +
	"update_ver\x18\b \x01(\x04R\tupdateVer\x12\x1d\n" +
	"\n" +
	"commit_ver\x18\t \x01(\x04R\tcommitVer\x12\x1a\n" +
	"\breplicas\x18\n" +
	" \x03(\tR\breplicas\x12\x1f\n" +
	"\vfrom_client\x18\v \x01(\bR\n" +
	"fromClient\x12\x18\n" +
	"\asyncing\x18\f \x01(\bR\asyncing\".\n" +
	"\x10PutChunkResponse\x12\x1a\n" +
	"\breplicas\x18\x01 \x03(\tR\breplicas\"Y\n" +
	"\x0fGetChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12+\n" +
	"\x11allow_uncommitted\x18\x02 \x01(\bR\x10allowUncommitted\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x15\n" +
	"\x13DeleteChunkResponse\"$\n" +
	"\fDrainRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"T\n" +
	"\rDrainResponse\x12)\n" +
	"\x10remaining_chunks\x18\x01 \x01(\x05R\x0fremainingChunks\x12\x18\n" +
	"\adrained\x18\x02 \x01(\bR\adrained\"\x0e\n" +
	"\fReadyRequest\"'\n" +
	"\rReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xae\n" +
	"\n" +
	"\bMemoryFS\x12A\n" +
	"\x06Health\x12\x1a.memoryfs.v1.HealthRequest\x1a\x1b.memoryfs.v1.HealthResponse\x12J\n" +
	"\tGetLeader\x12\x1d.memoryfs.v1.GetLeaderRequest\x1a\x1e.memoryfs.v1.GetLeaderResponse\x12J\n" +
	"\tListNodes\x12\x1d.memoryfs.v1.ListNodesRequest\x1a\x1e.memoryfs.v1.ListNodesResponse\x12;\n" +
	"\x04Join\x12\x18.memoryfs.v1.JoinRequest\x1a\x19.memoryfs.v1.JoinResponse\x12D\n" +
	"\aGetAttr\x12\x1b.memoryfs.v1.GetAttrRequest\x1a\x1c.memoryfs.v1.GetAttrResponse\x12A\n" +
	"\x06Lookup\x12\x1a.memoryfs.v1.LookupRequest\x1a\x1b.memoryfs.v1.LookupResponse\x12D\n" +
	"\aReaddir\x12\x1b.memoryfs.v1.ReaddirRequest\x1a\x1c.memoryfs.v1.ReaddirResponse\x12>\n" +
	"\x05Mkdir\x12\x19.memoryfs.v1.MkdirRequest\x1a\x1a.memoryfs.v1.MkdirResponse\x12A\n" +
	"\x06Create\x12\x1a.memoryfs.v1.CreateRequest\x1a\x1b.memoryfs.v1.CreateResponse\x12D\n" +
	"\aSymlink\x12\x1b.memoryfs.v1.SymlinkRequest\x1a\x1c.memoryfs.v1.SymlinkResponse\x12A\n" +
	"\x06Unlink\x12\x1a.memoryfs.v1.UnlinkRequest\x1a\x1b.memoryfs.v1.UnlinkResponse\x12>\n" +
	"\x05Rmdir\x12\x19.memoryfs.v1.RmdirRequest\x1a\x1a.memoryfs.v1.RmdirResponse\x12A\n" +
	"\x06Rename\x12\x1a.memoryfs.v1.RenameRequest\x1a\x1b.memoryfs.v1.RenameResponse\x12D\n" +
	"\aSetAttr\x12\x1b.memoryfs.v1.SetAttrRequest\x1a\x1c.memoryfs.v1.SetAttrResponse\x12I\n" +
	"\bPutChunk\x12\x1c.memoryfs.v1.PutChunkRequest\x1a\x1d.memoryfs.v1.PutChunkResponse(\x01\x12I\n" +
	"\bGetChunk\x12\x1c.memoryfs.v1.GetChunkRequest\x1a\x1d.memoryfs.v1.GetChunkResponse0\x01\x12P\n" +
	"\vDeleteChunk\x12\x1f.memoryfs.v1.DeleteChunkRequest\x1a .memoryfs.v1.DeleteChunkResponse\x12>\n" +
	"\x05Drain\x12\x19.memoryfs.v1.DrainRequest\x1a\x1a.memoryfs.v1.DrainResponse\x12>\n" +
	"\x05Ready\x12\x19.memoryfs.v1.ReadyRequest\x1a\x1a.memoryfs.v1.ReadyResponseB<Z:github.com/shaowenchen/memoryfs/api/memoryfs/v1;memoryfsv1b\x06proto3"

var (
	file_api_proto_memoryfs_v1_memoryfs_proto_rawDescOnce sync.Once
	file_api_proto_memoryfs_v1_memoryfs_proto_rawDescData []byte
)

func file_api_proto_memoryfs_v1_memoryfs_proto_rawDescGZIP() []byte {
	file_api_proto_memoryfs_v1_memoryfs_proto_rawDescOnce.Do(func() {
		file_api_proto_memoryfs_v1_memoryfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_memoryfs_v1_memoryfs_proto_rawDesc), len(file_api_proto_memoryfs_v1_memoryfs_proto_rawDesc)))
	})
	return file_api_proto_memoryfs_v1_memoryfs_proto_rawDescData
}

var file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_proto_memoryfs_v1_memoryfs_proto_goTypes = []any{
	(*Attr)(nil),                // 0: memoryfs.v1.Attr
	(*HealthRequest)(nil),       // 1: memoryfs.v1.HealthRequest
	(*HealthResponse)(nil),      // 2: memoryfs.v1.HealthResponse
	(*GetLeaderRequest)(nil),    // 3: memoryfs.v1.GetLeaderRequest
	(*GetLeaderResponse)(nil),   // 4: memoryfs.v1.GetLeaderResponse
	(*ListNodesRequest)(nil),    // 5: memoryfs.v1.ListNodesRequest
	(*ListNodesResponse)(nil),   // 6: memoryfs.v1.ListNodesResponse
	(*JoinRequest)(nil),         // 7: memoryfs.v1.JoinRequest
	(*JoinResponse)(nil),        // 8: memoryfs.v1.JoinResponse
	(*GetAttrRequest)(nil),      // 9: memoryfs.v1.GetAttrRequest
	(*GetAttrResponse)(nil),     // 10: memoryfs.v1.GetAttrResponse
	(*LookupRequest)(nil),       // 11: memoryfs.v1.LookupRequest
	(*LookupResponse)(nil),      // 12: memoryfs.v1.LookupResponse
	(*ReaddirRequest)(nil),      // 13: memoryfs.v1.ReaddirRequest
	(*ReaddirResponse)(nil),     // 14: memoryfs.v1.ReaddirResponse
	(*MkdirRequest)(nil),        // 15: memoryfs.v1.MkdirRequest
	(*MkdirResponse)(nil),       // 16: memoryfs.v1.MkdirResponse
	(*CreateRequest)(nil),       // 17: memoryfs.v1.CreateRequest
	(*CreateResponse)(nil),      // 18: memoryfs.v1.CreateResponse
	(*SymlinkRequest)(nil),      // 19: memoryfs.v1.SymlinkRequest
	(*SymlinkResponse)(nil),     // 20: memoryfs.v1.SymlinkResponse
	(*UnlinkRequest)(nil),       // 21: memoryfs.v1.UnlinkRequest
	(*UnlinkResponse)(nil),      // 22: memoryfs.v1.UnlinkResponse
	(*RmdirRequest)(nil),        // 23: memoryfs.v1.RmdirRequest
	(*RmdirResponse)(nil),       // 24: memoryfs.v1.RmdirResponse
	(*RenameRequest)(nil),       // 25: memoryfs.v1.RenameRequest
	(*RenameResponse)(nil),      // 26: memoryfs.v1.RenameResponse
	(*SetAttrRequest)(nil),      // 27: memoryfs.v1.SetAttrRequest
	(*SetAttrResponse)(nil),     // 28: memoryfs.v1.SetAttrResponse
	(*PutChunkRequest)(nil),     // 29: memoryfs.v1.PutChunkRequest
	(*PutChunkResponse)(nil),    // 30: memoryfs.v1.PutChunkResponse
	(*GetChunkRequest)(nil),     // 31: memoryfs.v1.GetChunkRequest
	(*GetChunkResponse)(nil),    // 32: memoryfs.v1.GetChunkResponse
	(*DeleteChunkRequest)(nil),  // 33: memoryfs.v1.DeleteChunkRequest
	(*DeleteChunkResponse)(nil), // 34: memoryfs.v1.DeleteChunkResponse
	(*DrainRequest)(nil),        // 35: memoryfs.v1.DrainRequest
	(*DrainResponse)(nil),       // 36: memoryfs.v1.DrainResponse
	(*ReadyRequest)(nil),        // 37: memoryfs.v1.ReadyRequest
	(*ReadyResponse)(nil),       // 38: memoryfs.v1.ReadyResponse
	nil,                         // 39: memoryfs.v1.ReaddirResponse.EntriesEntry
}
var file_api_proto_memoryfs_v1_memoryfs_proto_depIdxs = []int32{
	0,  // 0: memoryfs.v1.GetAttrResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 1: memoryfs.v1.LookupResponse.attr:type_name -> memoryfs.v1.Attr
	39, // 2: memoryfs.v1.ReaddirResponse.entries:type_name -> memoryfs.v1.ReaddirResponse.EntriesEntry
	0,  // 3: memoryfs.v1.MkdirResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 4: memoryfs.v1.CreateResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 5: memoryfs.v1.SymlinkResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 6: memoryfs.v1.UnlinkResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 7: memoryfs.v1.SetAttrRequest.attr:type_name -> memoryfs.v1.Attr
	0,  // 8: memoryfs.v1.SetAttrResponse.attr:type_name -> memoryfs.v1.Attr
	0,  // 9: memoryfs.v1.ReaddirResponse.EntriesEntry.value:type_name -> memoryfs.v1.Attr
	1,  // 10: memoryfs.v1.MemoryFS.Health:input_type -> memoryfs.v1.HealthRequest
	3,  // 11: memoryfs.v1.MemoryFS.GetLeader:input_type -> memoryfs.v1.GetLeaderRequest
	5,  // 12: memoryfs.v1.MemoryFS.ListNodes:input_type -> memoryfs.v1.ListNodesRequest
	7,  // 13: memoryfs.v1.MemoryFS.Join:input_type -> memoryfs.v1.JoinRequest
	9,  // 14: memoryfs.v1.MemoryFS.GetAttr:input_type -> memoryfs.v1.GetAttrRequest
	11, // 15: memoryfs.v1.MemoryFS.Lookup:input_type -> memoryfs.v1.LookupRequest
	13, // 16: memoryfs.v1.MemoryFS.Readdir:input_type -> memoryfs.v1.ReaddirRequest
	15, // 17: memoryfs.v1.MemoryFS.Mkdir:input_type -> memoryfs.v1.MkdirRequest
	17, // 18: memoryfs.v1.MemoryFS.Create:input_type -> memoryfs.v1.CreateRequest
	19, // 19: memoryfs.v1.MemoryFS.Symlink:input_type -> memoryfs.v1.SymlinkRequest
	21, // 20: memoryfs.v1.MemoryFS.Unlink:input_type -> memoryfs.v1.UnlinkRequest
	23, // 21: memoryfs.v1.MemoryFS.Rmdir:input_type -> memoryfs.v1.RmdirRequest
	25, // 22: memoryfs.v1.MemoryFS.Rename:input_type -> memoryfs.v1.RenameRequest
	27, // 23: memoryfs.v1.MemoryFS.SetAttr:input_type -> memoryfs.v1.SetAttrRequest
	29, // 24: memoryfs.v1.MemoryFS.PutChunk:input_type -> memoryfs.v1.PutChunkRequest
	31, // 25: memoryfs.v1.MemoryFS.GetChunk:input_type -> memoryfs.v1.GetChunkRequest
	33, // 26: memoryfs.v1.MemoryFS.DeleteChunk:input_type -> memoryfs.v1.DeleteChunkRequest
	35, // 27: memoryfs.v1.MemoryFS.Drain:input_type -> memoryfs.v1.DrainRequest
	37, // 28: memoryfs.v1.MemoryFS.Ready:input_type -> memoryfs.v1.ReadyRequest
	2,  // 29: memoryfs.v1.MemoryFS.Health:output_type -> memoryfs.v1.HealthResponse
	4,  // 30: memoryfs.v1.MemoryFS.GetLeader:output_type -> memoryfs.v1.GetLeaderResponse
	6,  // 31: memoryfs.v1.MemoryFS.ListNodes:output_type -> memoryfs.v1.ListNodesResponse
	8,  // 32: memoryfs.v1.MemoryFS.Join:output_type -> memoryfs.v1.JoinResponse
	10, // 33: memoryfs.v1.MemoryFS.GetAttr:output_type -> memoryfs.v1.GetAttrResponse
	12, // 34: memoryfs.v1.MemoryFS.Lookup:output_type -> memoryfs.v1.LookupResponse
	14, // 35: memoryfs.v1.MemoryFS.Readdir:output_type -> memoryfs.v1.ReaddirResponse
	16, // 36: memoryfs.v1.MemoryFS.Mkdir:output_type -> memoryfs.v1.MkdirResponse
	18, // 37: memoryfs.v1.MemoryFS.Create:output_type -> memoryfs.v1.CreateResponse
	20, // 38: memoryfs.v1.MemoryFS.Symlink:output_type -> memoryfs.v1.SymlinkResponse
	22, // 39: memoryfs.v1.MemoryFS.Unlink:output_type -> memoryfs.v1.UnlinkResponse
	24, // 40: memoryfs.v1.MemoryFS.Rmdir:output_type -> memoryfs.v1.RmdirResponse
	26, // 41: memoryfs.v1.MemoryFS.Rename:output_type -> memoryfs.v1.RenameResponse
	28, // 42: memoryfs.v1.MemoryFS.SetAttr:output_type -> memoryfs.v1.SetAttrResponse
	30, // 43: memoryfs.v1.MemoryFS.PutChunk:output_type -> memoryfs.v1.PutChunkResponse
	32, // 44: memoryfs.v1.MemoryFS.GetChunk:output_type -> memoryfs.v1.GetChunkResponse
	34, // 45: memoryfs.v1.MemoryFS.DeleteChunk:output_type -> memoryfs.v1.DeleteChunkResponse
	36, // 46: memoryfs.v1.MemoryFS.Drain:output_type -> memoryfs.v1.DrainResponse
	38, // 47: memoryfs.v1.MemoryFS.Ready:output_type -> memoryfs.v1.ReadyResponse
	29, // [29:48] is the sub-list for method output_type
	10, // [10:29] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_memoryfs_v1_memoryfs_proto_init() }
func file_api_proto_memoryfs_v1_memoryfs_proto_init() {
	if File_api_proto_memoryfs_v1_memoryfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_memoryfs_v1_memoryfs_proto_rawDesc), len(file_api_proto_memoryfs_v1_memoryfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_memoryfs_v1_memoryfs_proto_goTypes,
		DependencyIndexes: file_api_proto_memoryfs_v1_memoryfs_proto_depIdxs,
		MessageInfos:      file_api_proto_memoryfs_v1_memoryfs_proto_msgTypes,
	}.Build()
	File_api_proto_memoryfs_v1_memoryfs_proto = out.File
	file_api_proto_memoryfs_v1_memoryfs_proto_goTypes = nil
	file_api_proto_memoryfs_v1_memoryfs_proto_depIdxs = nil
}
